[package]
name = "waffle"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_6"] }
itertools = "0.13.0"
enum-iterator = "2.1.0"

[build-dependencies]
glib-build-tools = "0.19.0"
